### ISSUE TITLE
Made a simple run command script 

### ISSUE THREAD

**Issue by ghost** [nikolausmayer/cmake-templates#1]
Hi, for the people using this handy template, i made a simple bash script to build and execute your program. You only have to change the executable name, thats it! put the file in the generic-cmake-example folder, open it and edit the line "EXEC_NAME=MarkerDetection". 

run the following commands in the generic-cmake-example-folder 
`sudo chmod +x run`
`./run`

[run.zip](https://github.com/nikolausmayer/cmake-templates/files/2474249/run.zip)

**Comment by nikolausmayer** [comment]
Hi,

thanks for your efforts! Please allow me to point out a few issues with the script:
- it only works once the `mkdir build` and `cmake ..` steps have been executed (see main README)
- it does not handle paths with spaces etc correctly
- it does not handle errors, e.g. if `make -j` fails
- (it is not portable shell code as it relies on e.g. the availability of `$(...)`, but that's a pet peeve of mine)
- the `sleep 5` line does not seem to have a purpose

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
