### ISSUE TITLE
Slight modification Run script from feedback

### ISSUE THREAD

**Issue by ghost** [nikolausmayer/cmake-templates#2]
**To the owner of this repo:** 
I took your good template and slightly modified to work with the run script. also made tiny alteration to support recursive include folders or sub-modules. And i changed the run script with your feedback. 

**regular:**
https://gitlab.com/ArsalanAnwari/cmake-workspace

**netbeans:**
https://gitlab.com/ArsalanAnwari/cmake-workspace/tree/Netbeans

**ros with catkin:**
https://gitlab.com/ArsalanAnwari/cmake-workspace/tree/Netbeans

If you have any more feedback or changes i need to make to the run script etc. please let me know. I loved to help you out with simple scripts etc you'll need

**Comment by nikolausmayer** [comment]
I would like to take a look at your new scripts, but the links do not seem to point anywhere.

**Comment by ghost** [comment]
Ahh my bad i had the links point to a private group repo. Ill fix the comment!

**Comment by ghost** [comment]
> I would like to take a look at your new scripts, but the links do not seem to point anywhere.

I have changed the links
